pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage('Build') {
            steps {
                dir("starwarapi") {
                bat 'mvn clean package'
            }
         }
        }
         stage('Test') {
            steps {
                sh 'success'
            }
        }
        stage('Build Docker Image') {
            steps {
                bat 'docker build -t starwarapi .'
                bat 'docker login -u $dockerhub_USR --password-stdin'
                bat 'docker tag starwarapi suryaveersingh/starwarapi'
                bat 'docker image push suryaveersingh/starwarapi'
            }
        }
        stage('Deploy Docker') {
            steps {
                bat 'docker stop starwarapi | true'
                bat 'docker rm starwarapi | true'
                bat 'docker run --name starwarapi -d -p 8086:8086 suryaveersingh/starwarapi'
            }
        }
    }
}