pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage('Build') {
            steps {
                sh 'cd starwarapi'
                sh 'mvn clean package'
            }
        }
         stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t starwarapi .'
                sh 'docker login -u $dockerhub_USR --password-stdin'
                sh 'docker tag starwarapi suryaveersingh/starwarapi'
                sh 'docker image push suryaveersingh/starwarapi'
            }
        }
        stage('Deploy Docker') {
            steps {
                sh 'docker stop starwarapi | true'
                sh 'docker rm starwarapi | true'
                sh 'docker run --name starwarapi -d -p 8086:8086 suryaveersingh/starwarapi'
            }
        }
    }
}