server:
  port: 8087

spring:
  security:
    username: admin
    password: ENC(rMXdXHk58MdPDuTHhQLl7w==)

  datasource:
    username: surya
    password: ENC(57JNBOZxv4EcKQOBGvbE1w==)

jasypt:
  encryptor:
    password: suryaveerkk